name: Run Benchmarks and Save

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM 21
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod  x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y libpolly-21-dev
          rm ./llvm.sh

      - name: Setup Rust toolchain and cache
        uses: Swatinem/rust-cache@v2

      - name: Run benchmark
        run: cargo bench

      - name: Prepare Benchmark Reports
        run: |
          mkdir -p ./out-bench
          if [ -d "./target/criterion/report" ]; then
            cp -r ./target/criterion/report/* ./out-bench/
          fi

      - name: Deploy to bench-results branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out-bench
          publish_branch: bench-results
          commit_message: "[bot] update bench results ${{ github.sha }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'