name: Run Benchmarks and save

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install llvm
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y libpolly-21-dev

    - name: setup git
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 524288000
    
    - name: run benchmark
      run: cargo bench

    - name: save output
      run: |
          mkdir ~/bench-output-temp
          if [ -d "./target/criterion/report" ]; then
            cp -r ./target/criterion/report/* ~/bench-output-temp/
          else
            echo "Benchmark report not found!"
            exit 1
          fi

          git fetch origin
          git checkout bench-results || git checkout --orphan bench-results

          git rm -rf .

          cp -r ~/bench-output-temp/* .

          git add .
          git commit -m "[bot] update bench results: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin bench-results
