name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install LLVM 21
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y libpolly-21-dev
          rm ./llvm.sh

      - name: Setup Rust default toolchain and cache
        uses: Swatinem/rust-cache@v2

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri

      - name: Build
        run: cargo +stable build --verbose

      - name: Check formatting
        run: cargo +stable fmt --all -- --check

      - name: Clippy
        run: cargo +stable clippy -- -D warnings

      - name: Run Miri
        run: |
          cargo +nightly miri setup
          cargo +nightly miri test --lib
        env:
          MIRIFLAGS: "-Zmiri-ignore-leaks" 

      - name: Test
        run: cargo +stable test --verbose

      - name: Run benchmark
        run: cargo +stable bench

      - name: Setup out directory
        run: mkdir -p ./out

      - name: Prepare Benchmark Reports
        run: |
          mkdir -p ./out/benches
          if [ -d "./target/criterion" ]; then
            cp -r ./target/criterion/* ./out/benches
          fi

      - name: Deploy to bench-results branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          commit_message: "[bot] update bench results ${{ github.sha }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
